#激活环境
spring.profiles.active=dev

server.port=8080
spring.application.name=example

#AES加密用的KEY
#这条必须存在
jasypt.encryptor.password=ABCDEFGHIJKLMNOP
#自定义加密的key
AESKEY=ABCDEFGHIJKLMNOP

mybatis.mapper-locations=classpath:mapper/*.xml

management.endpoints.web.exposure.include=*

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

blank.parameter.check.logger=false